travel_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('travel_blogs.urls')),
    path('users/', include('users.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

travel_blogs/urls.py
"""Define URL patterns for travel blogs. """

from django.urls import path
from . import views

app_name = 'travel_blogs'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),

    # Page that displays all travel topics
    path('topics/', views.topics, name='topics'),

    # Detail page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Page for adding a new topic
    path('new_topic/', views.new_topic, name='new_topic'),

    # Page for adding a new entry
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Page for editing an entry
    path('edit_entry/int:<entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines url patterns for users"""
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),

]

travel_blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
	"""A travel topic the user wants to share with the world."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""Return a string representation of the model."""
		return self.text


class Entry(models.Model):
	"""Detailed post about the topic"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Return a string representation of the model."""
		return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

travel_blogs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        # This widget overrides Djangos default widget to make the page customizable
        # Gives users the space to write a meaningful entry
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

travel_blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Travel Blog."""
    return render(request, 'travel_blogs/index.html')

# checks whether user is logged in
# if not user is redirected to login page


@login_required
def topics(request):
    """Show all Topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'travel_blogs/topics.html', context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Makes sure the topic belongs to the current user.
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'travel_blogs/topic.html', context)


@login_required
def new_topic(request):
    """Add a new topic."""

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('travel_blogs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'travel_blogs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    new = EntryForm(data=request.POST)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = new
        if form.is_valid():
            new_entry = form.save(commit=False)

            new_entry.topic = topic
            new_entry.save()
            return redirect('travel_blogs:topic', topic_id=topic_id)

    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'travel_blogs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # Protect pages to avoid users access to entries that don't match their user ID
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        """Initial Request; pre-fills the form with the current entry """
        form = EntryForm(instance=entry)
    else:
        """POST data submitted. Process the data"""
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('travel_blogs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'travel_blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display a blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to the home page
            login(request, new_user)
            return redirect('travel_blogs:index')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

travel_blogs/templates/travel_blogs/base.html
<!---The parent template; contains common elements to all pages
Other templates will inherit from this page--->
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TRAVEL BLOG</title>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

  </head>
  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'travel_blogs:index'%}">Travel Blog</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'travel_blogs:topics' %}">
                  All Topics</a></li>

          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <span class="navbar-text">Hello, {{ user.username }}.</span>
              </li>
              <li class="'nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div>
    </nav>

<main role="main" class="container">
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
  </div>
  <div>
    {% block content %}{% endblock content %}
  </div>
</main>

  </body>
</html>

travel_blogs/templates/travel_blogs/edit_entry.html
{% extends "travel_blogs/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Entry</title>
</head>
<body>

{% block content %}

    <p><a href="{url 'travel_blogs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit Entry:</p>
    <form action="{% url 'travel_blogs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}
</body>
</html>

travel_blogs/templates/travel_blogs/index.html
{% extends "travel_blogs/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TRAVEL BLOG</title>
  </head>
  <body>

<main>
{% block page_header %}
    {% if user.is_authenticated %}
    <div class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'costa_rica.jpg' %}" class="d-block w-100" alt="Costa Rica">
            </div>
            <div class="carousel-item">
                <img src="{% static 'sweden.jpg' %}" class="d-block w-100" alt="Sweden">
            </div>
            <div class="carousel-item">
                <img src="{% static 'dubai.jpg' %}" class="d-block w-100" alt="Dubai">
            </div>
        </div>
    </div>
    {% else %}
    <div class="jumbotron">
      <h1 class="display-3">Keep Track Of All Your Vacations.</h1>

      <p class="lead">TRAVEL BLOG is made for adventure-loving travelers who want to have a space to keep all
            of their destination memories in one place.</p>

      <a class="btn btn-lg btn-outline-primary" href="{% url 'users:register' %}"
         role="button">Sign Up &raquo;</a>
    {% endif %}
    </div>

{% endblock page_header %}

</main>

  </body>
</html>

travel_blogs/templates/travel_blogs/new_entry.html
{% extends "travel_blogs/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>New Entry</title>
</head>
<body>

{% block content %}

  <p><a href="{% url 'travel_blogs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Add a new entry:</p>
  <form action="{% url 'travel_blogs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>Add entry</button>
  </form>

{% endblock content %}
</body>
</html>

travel_blogs/templates/travel_blogs/new_topic.html
{% extends "travel_blogs/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
</head>
<body>

{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'travel_blogs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}
</body>
</html>

travel_blogs/templates/travel_blogs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Topics</title>
{% extends 'travel_blogs/base.html' %}
</head>
<body>

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'travel_blogs:new_entry' topic.id %}">Add new entry</a>
  </p>

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'travel_blogs:edit_entry' entry.id %}">
            edit entry</a> </small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}

{% endblock content %}
</body>
</html>

travel_blogs/templates/travel_blogs/topics.html
{% extends "travel_blogs/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Topics</title>
</head>
<body>

{% block page_header %}
  <h1>All Travel Destinations</h1>
{% endblock page_header %}

{% block content %}
<h5>Add more destinations below.</h5>
<h5><a href="{% url 'travel_blogs:new_topic' %}">Add a new topic</a></h5>
<br><br>

  <div class="card" style="width: 18rem;">
  <ul class="list-group list-group-flush">
    {% for topic in topics %}
    <li class="list-group-item">
      <a href="{% url 'travel_blogs:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
      <h3>No topics have been added yet.</h3>
    {% endfor %}
  </ul>
</div>

{% endblock content %}
</body>
</html>